project_id = "oyeecjsbyuodlwqqzqkm"

[functions.get-orders]
verify_jwt = true

[functions.send-order-email]
verify_jwt = true

[functions.mcp]
verify_jwt = false

[functions.help-chat]
verify_jwt = false
