// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyeecjsbyuodlwqqzqkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95ZWVjanNieXVvZGx3cXF6cWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NjQ2ODAsImV4cCI6MjA5NjE0MDY4MH0.2hylJhqw4sC3QgZTQREHZtMYZ-80TJ-hrCfoRNjE3z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});